version: 2
jobs:
    build:
        docker:
            - image: circleci/node:14.9-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "package.json" }}-{{ checksum "rn-vector/package.json"}}
                      - v2-dependencies-
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install
                      cd rn-vector && yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v2-dependencies-{{ checksum "package.json" }}-{{ checksum "rn-vector/package.json"}}
            - run:
                  name: Build Packages
                  command: | 
                      yarn build
                      cd rn-vector && yarn build
            - run:
                  name: Verify SVG Build Artifacts
                  command: yarn test
            - persist_to_workspace:
                  root: .
                  paths:
                      - iconfont
                      - svg
                      - rn-vector

    publish:
        docker:
            - image: circleci/node:14.9-browsers
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: Authenticate with registry
                  command: |
                      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                      echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                  name: Publish @pxblue/icons
                  command: yarn publish:package -b $CIRCLE_BRANCH
            - run:
                  name: Publish @pxblue/icons-svg
                  command: cd svg && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                  name: Publish @pxblue/react-native-vector-icons
                  command: cd rn-vector && yarn publish:package -b $CIRCLE_BRANCH
workflows:
    version: 2
    icons:
        jobs:
            - build
            - publish_:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                              - dev
